foo -> boost::throw_exception
boost::throw_exception ->
