boost::throw_exception ->
foo -> boost::throw_exception
